---
title: "TITLE"
author: "Matthias Uckert"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
format:
 html:
  code-fold: show
  toc-location: left
  toc: true
  toc-depth: 3
  toc-expand: true
  page-layout: full
  code-overflow: wrap
  code-line-numbers: true
  code-copy: true
---


```{r setup, include=FALSE, purl=FALSE}
.name_script <- "AAAAAAA"

.dir_here <- normalizePath(here::here())
.dir_out  <- file.path(.dir_here, file.path("2_output/", .name_script))

knitr::opts_knit$set(root.dir = .dir_here) 
knitr::opts_chunk$set(root.dir = .dir_here) 
rUtils::dloc(.dir_out, .init = TRUE)
.__init__
```

# Description

Fill Description

# Project Setup

```{r Project Setup, message=FALSE, warning=FALSE}
library <- function(...) suppressPackageStartupMessages(base::library(...))

library(tidyverse); library(rUtils); library(rCache)
options(scipen = 999)
.path_fun <- use_functions(.dir_here, NULL, .name_script)
.path_fun
```


# Code

## Header 1
```{r}

```

## Header 2
```{r}

```


# Save Output
```{r}
lst_save <- list()
```


# Output Table Overview
```{r}
lst_desc <- list()
```

```{r, include=FALSE}
#  DON'T DELETE, THIS IS NEEDED FOR DEPENDENCIES
library(DT)
htmltools::tagList(datatable(mtcars))
```

::: {.panel-tabset}
```{r Output Descriptives}
#| results: asis
#| warning: false
#| message: false
for (i in seq_len(length(lst_desc))) {
  cat(paste0("## Table: ", names(lst_desc)[i], "\n\n"))
  print(htmltools::tagList(
    futils_format_dt(lst_desc[[i]], .cd0 = 3:4, .cd4 = 6:12, .cp = 5),
    htmltools::tags$style(".dataTables_wrapper {font-size: 12px;}")
  ))
}
```
:::

```{r}
#| results: asis
vec_funs <- ls()
for (i in seq_len(length(vec_funs))) {
  cat("\n\n\nFunction:", vec_funs[i], "\n\n")
  cat(prettycode::highlight(deparse(get(vec_funs[i], globalenv()))), sep = "\n")
}
```

